@startuml
[*] --> State1
State1 --> State2 : GoFurther

State2 -> State2 : Stay

State2 -> State1 : GoFurther

State1 : OnEnter : Entering1
State1 : OnExit : Exiting1
State2 : OnEnter : Entering2
State2 : OnExit : Exiting2

@enduml