@startuml
state SuperParent {
Parental: OnEnter : Action
}


state Parental {
[*] --> State1
}
State1 ----> State2 : GoFurther
State2 -> State2 : Stay

State2 -> State1 : GoFurther

State1 : OnEnter : OperationA
State1 : OnExit : OperationC
State1 : OnLeaf : OperationB
State2 : OnEnter : OperationD
State2 : OnExit : OperationF
State2 : OnLeaf : OperationE
@enduml